const profiles = [
    {
      "id": 1,
      "name": "Anders",
      "last_name": "Pedersen",
      "age": 27,
      "gender": "Male",
      "looking_for": "Women",
      "location": "Copenhagen",
      "hometown": "Aalborg",
      "education_level": "Master's degree",
      "occupation": "Financial analyst",
      "zodiac_sign": "Leo",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Photography", "Traveling", "Yoga", "Cooking", "Music", "Technology"],
      "children": "1",
      "image": "./images/profile-photos/user-image(13).png",
      "profile_text": "I'm a financial analyst with a passion for photography, travel, and technology. I'm looking for a woman who shares my interests and can join me on exciting adventures."
    },
    {
      "id": 2,
      "name": "Maja",
      "last_name": "Petersen",
      "age": 26,
      "gender": "Female",
      "looking_for": "Both",
      "location": "Copenhagen",
      "hometown": "Aarhus",
      "education_level": "Master's degree",
      "occupation": "Journalist",
      "zodiac_sign": "Taurus",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Painting", "Literature", "Yoga", "Animals", "Fashion and design", "Volunteering and charity work"],
      "children": "3 or more",
      "image": "./images/profile-photos/user-image(3).png",
      "profile_text": "I'm a creative and sensitive person who enjoys expressing myself through art and writing. I also love animals and fashion and enjoy giving back to society and helping those in need. I'm looking for a person who's open and empathetic and can understand me and my creativity."
    },
    {
      "id": 3,
      "name": "Maria",
      "last_name": "Olsen",
      "age": 24,
      "gender": "Female",
      "looking_for": "Men",
      "location": "Aarhus",
      "hometown": "Vejle",
      "education_level": "Associate degree",
      "occupation": "Marketing coordinator",
      "zodiac_sign": "Aries",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Painting", "Traveling", "Yoga", "Cooking", "Hiking and outdoor activities"],
      "children": "none",
      "image": "./images/profile-photos/user-image(4).png",
      "profile_text": "I'm an energetic and creative person who loves to be active and challenge myself. I like to cook healthy food and come up with new recipes, and enjoy staying fit and in shape by doing yoga and hiking. I'm looking for a man who can appreciate my positive attitude and strengthen me both physically and mentally."
    },
    {
      "id": 4,
      "name": "Louise",
      "last_name": "Mortensen",
      "age": 29,
      "gender": "Female",
      "looking_for": "Both",
      "location": "Copenhagen",
      "hometown": "Esbjerg",
      "education_level": "Master's degree",
      "occupation": "Non-profit manager",
      "zodiac_sign": "Sagittarius",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Traveling", "Cooking", "Yoga", "Volunteering and charity work"],
      "children": "none",
      "image": "./images/profile-photos/user-image(5).png",
      "profile_text": "I'm a helpful and active person who'd like to make a difference in the world. I love traveling and experiencing new cultures and enjoy helping others through volunteering and charity work. I'm looking for a person who has the same attitude and is ready to take the world by storm together with me."
    },
    {
      "id": 5,
      "name": "Carsten",
      "last_name": "Poulsen",
      "age": 25,
      "gender": "Male",
      "looking_for": "Men",
      "location": "Copenhagen",
      "hometown": "Odense",
      "education_level": "Master's degree",
      "occupation": "Event coordinator",
      "zodiac_sign": "Leo",
      "alcohol_habits": "In the weekends if I have fun plans",
      "smoking_habits": "Non-smoker",
      "interests": ["Traveling", "Cooking", "Yoga", "Music"],
      "children": "1",
      "image": "./images/profile-photos/user-image(19).png",
      "profile_text": "I'm a creative and outgoing person who likes to take long hikes in the mountains and cook healthy food at home. I'm looking for a man who can appreciate my positive attitude and fun personality, and who likes to stay active and healthy."
    },
    {
      "id": 6,
      "name": "Clara",
      "last_name": "Poulsen",
      "age": 26,
      "gender": "Female",
      "looking_for": "Men",
      "location": "Copenhagen",
      "hometown": "Odense",
      "education_level": "Master's degree",
      "occupation": "Event coordinator",
      "zodiac_sign": "Leo",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Traveling", "Cooking", "Yoga", "Music"],
      "children": "2",
      "image": "./images/profile-photos/user-image(7).png",
      "profile_text": "I'm a creative and outgoing person who likes to take long hikes in the mountains and cook healthy food at home. I'm looking for a man who can appreciate my positive attitude and fun personality and who likes to stay active and healthy."
    },
    {
      "id": 7,
      "name": "Ida",
      "last_name": "Jensen",
      "age": 28,
      "gender": "Female",
      "looking_for": "Men",
      "location": "Aarhus",
      "hometown": "Silkeborg",
      "education_level": "Associate degree",
      "occupation": "Social media manager",
      "zodiac_sign": "Aquarius",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Yoga", "Traveling", "Cooking"],
      "children": "3 or more",
      "image": "./images/profile-photos/user-image(8).png",
      "profile_text": "I'm a curious and open-minded person who likes to explore new places and cultures. I also enjoy cooking and preparing healthy meals, and like to stay in shape by practicing yoga. I'm looking for a man who can share my thirst for adventure and passion for health and well-being."
    },
    {
      "id": 8,
      "name": "Laura",
      "last_name": "Poulsen",
      "age": 26,
      "gender": "Female",
      "looking_for": "Both",
      "location": "Odense",
      "hometown": "Aarhus",
      "education_level": "Master's degree",
      "occupation": "Graphic designer",
      "zodiac_sign": "Virgo",
      "alcohol_habits": "Non-drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Painting", "Literature", "Yoga", "Arts and crafts", "Music", "Hiking and outdoor activities"],
      "children": "1",
      "image": "./images/profile-photos/user-image(9).png",
      "profile_text": "I'm a creative and curious person who likes to learn new things and express myself through art and writing."
    },
    {
      "id": 9,
      "name": "Anna",
      "last_name": "Larsen",
      "age": 25,
      "gender": "Female",
      "looking_for": "Men",
      "location": "Aarhus",
      "hometown": "Aalborg",
      "education_level": "Associate degree",
      "occupation": "Personal trainer",
      "zodiac_sign": "Aquarius",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Yoga", "Cooking", "Hiking and outdoor activities"],
      "children": "none",
      "image": "./images/profile-photos/user-image(10).png",
      "profile_text": "I'm a creative and outgoing person who likes to take long hikes in the mountains and cook healthy food at home. I'm looking for a man who can appreciate my positive attitude and fun personality and who likes to stay active and healthy."
    },
    {
      "id": 10,
      "name": "Jason",
      "last_name": "Hansen",
      "age": 32,
      "gender": "Female",
      "looking_for": "Men",
      "location": "Aalborg",
      "hometown": "Hjørring",
      "education_level": "Master's degree",
      "occupation": "Psychologist",
      "zodiac_sign": "Libra",
      "alcohol_habits": "Only for special occasions",
      "smoking_habits": "Smoker",
      "interests": ["Psychology", "Traveling", "Yoga", "Cooking", "Music", "Hiking and outdoor activities"],
      "children": "1",
      "image": "./images/profile-photos/user-image(14).png",
      "profile_text": "I'm a psychologist who's passionate about understanding people and helping them lead better lives. I'm looking for a man who's intellectually curious and ready to explore the depths of the human mind with me."
    },
   
    {
      "id": 11,
      "name": "Peter",
      "last_name": "Madsen",
      "age": 31,
      "gender": "Male",
      "looking_for": "Women",
      "location": "Aarhus",
      "hometown": "Aalborg",
      "education_level": "Bachelor's degree",
      "occupation": "Architect",
      "zodiac_sign": "Pisces",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Architecture", "Traveling", "Yoga", "Music", "Hiking and outdoor activities"],
      "children": "2",
      "image": "./images/profile-photos/user-image(12).png",
      "profile_text": "I'm an architect who's passionate about creating beautiful spaces and exploring the world. I'm looking for a woman who appreciates design and is ready to embark on adventures with me."
    },
    {
      "id": 12,
      "name": "Lærke",
      "last_name": "Christensen",
      "age": 53,
      "gender": "Female",
      "looking_for": "Both",
      "location": "Aarhus",
      "hometown": "Copenhagen",
      "education_level": "Doctorate",
      "occupation": "Research scientist",
      "zodiac_sign": "Aquarius",
      "alcohol_habits": "Non-drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Photography", "Literature", "Traveling", "Cooking", "Yoga", "Arts and crafts"],
      "children": "2",
      "image": "./images/profile-photos/user-image(2).png",
      "profile_text": "I'm a thoughtful and curious person with a passion for exploring and learning new things. I enjoy taking pictures and writing, and when I need to relax, you can often find me on my yoga mat or in the kitchen. I'm looking for a person who can take me on new adventures and share my love for art and culture."
    },
    {
      "id": 13,
      "name": "Simon",
      "last_name": "Mortensen",
      "age": 28,
      "gender": "Male",
      "looking_for": "Women",
      "location": "Copenhagen",
      "hometown": "Esbjerg",
      "education_level": "Master's degree",
      "occupation": "Non-profit manager",
      "zodiac_sign": "Sagittarius",
      "alcohol_habits": "Only for special occasions",
      "smoking_habits": "Smoker",
      "interests": ["Traveling", "Cooking", "Yoga", "Volunteering and charity work"],
      "children": "none",
      "image": "./images/profile-photos/user-image(17).png",
      "profile_text": "I'm a helpful and active person who'd like to make a difference in the world. I love traveling and experiencing new cultures and enjoy helping others through volunteering and charity work. I'm looking for a person who has the same attitude and is ready to take the world by storm together with me."
    },
    {
      "id": 10,
      "name": "David",
      "last_name": "Jensen",
      "age": 56,
      "gender": "Male",
      "looking_for": "Women",
      "location": "Copenhagen",
      "hometown": "Aarhus",
      "education_level": "Master's degree",
      "occupation": "Software engineer",
      "zodiac_sign": "Virgo",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Photography", "Traveling", "Yoga", "Cooking", "Music", "Technology"],
      "children": "1",
      "image": "./images/profile-photos/user-image(11).png",
      "profile_text": "I'm a software engineer with a passion for photography, travel, and technology. I'm looking for a woman who shares my interests and can join me on exciting adventures."
    },
  
    {
      "id": 15,
      "name": "Søren",
      "last_name": "Olsen",
      "age": 28,
      "gender": "Male",
      "looking_for": "Women",
      "location": "Copenhagen",
      "hometown": "Vejle",
      "education_level": "Bachelor's degree",
      "occupation": "Teacher",
      "zodiac_sign": "Sagittarius",
      "alcohol_habits": "In the weekends if I have fun plans",
      "smoking_habits": "Non-smoker",
      "interests": ["Teaching", "Traveling", "Yoga", "Cooking", "Music", "Hiking and outdoor activities"],
      "children": "2",
      "image": "./images/profile-photos/user-image(15).png",
      "profile_text": "I'm a teacher who's passionate about education and enjoys helping young minds grow. On the weekends, I like to have fun and enjoy life to the fullest. I'm looking for a woman who shares my love for learning and adventure."
    },
    {
      "id": 16,
      "name": "Lone",
      "last_name": "Andreasen",
      "age": 33,
      "gender": "Female",
      "looking_for": "Men",
      "location": "Aalborg",
      "hometown": "Hjørring",
      "education_level": "Bachelor's degree",
      "occupation": "Art teacher",
      "zodiac_sign": "Leo",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Photography", "Traveling", "Yoga", "Arts and crafts", "Animals", "Astrology"],
      "children": "none",
      "image": "./images/profile-photos/user-image(6).png",
      "profile_text": "I'm an adventurous and creative person who loves to explore new cultures and create art. I'm also very interested in astrology and often spend my time reading about stars and planets. I'm looking for a person who can be my travel companion and share my passion for exploring and learning new things."
    },
    {
      "id": 17,
      "name": "Joseph",
      "last_name": "Christensen",
      "age": 30,
      "gender": "Female",
      "looking_for": "Both",
      "location": "Aarhus",
      "hometown": "Copenhagen",
      "education_level": "Doctorate",
      "occupation": "Research scientist",
      "zodiac_sign": "Aquarius",
      "alcohol_habits": "Non-drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Photography", "Literature", "Traveling", "Cooking", "Yoga", "Arts and crafts"],
      "children": "2",
      "image": "./images/profile-photos/user-image(16).png",
      "profile_text": "I'm a thoughtful and curious person with a passion for exploring and learning new things. I enjoy taking pictures and writing, and when I need to relax, you can often find me on my yoga mat or in the kitchen. I'm looking for a person who can take me on new adventures and share my love for art and culture."
    },
    {
      "id": 18,
      "name": "Jonas",
      "last_name": "Andreasen",
      "age": 29,
      "gender": "Male",
      "looking_for": "Women",
      "location": "Aalborg",
      "hometown": "Hjørring",
      "education_level": "Bachelor's degree",
      "occupation": "Art teacher",
      "zodiac_sign": "Leo",
      "alcohol_habits": "Typically every evening",
      "smoking_habits": "Social smoker",
      "interests": ["Photography", "Traveling", "Yoga", "Arts and crafts", "Animals", "Astrology"],
      "children": "none",
      "image": "./images/profile-photos/user-image(18).png",
      "profile_text": "I'm an adventurous and creative person who loves to explore new cultures and create art. I'm also very interested in astrology and often spend my time reading about stars and planets. I'm looking for a person who can be my travel companion and share my passion for exploring and learning new things."
    },
    {
      "id": 19,
      "name": "Jørgen",
      "last_name": "Jensen",
      "age": 27,
      "gender": "Female",
      "looking_for": "Men",
      "location": "Copenhagen",
      "hometown": "Aarhus",
      "education_level": "Master's degree",
      "occupation": "Software engineer",
      "zodiac_sign": "Virgo",
      "alcohol_habits": "Social drinker",
      "smoking_habits": "Non-smoker",
      "interests": ["Photography", "Traveling", "Yoga", "Cooking", "Music", "Technology"],
      "children": "1",
      "image": "./images/profile-photos/user-image(19).png",
      "profile_text": "I'm a software engineer with a passion for photography, travel, and technology. I'm looking for a man who shares my interests and can join me on exciting adventures."
    },
    {
      "id": 20,
      "name": "Frederik",
      "last_name": "Jensen",
      "age": 47,
      "gender": "Male",
      "looking_for": "Women",
      "location": "Aarhus",
      "hometown": "Silkeborg",
      "education_level": "Associate degree",
      "occupation": "Social media manager",
      "zodiac_sign": "Aquarius",
      "alcohol_habits": "Typically every evening",
      "smoking_habits": "Smoker",
      "interests": ["Yoga", "Traveling", "Cooking"],
      "children": "3 or more",
      "image": "./images/profile-photos/user-image(20).png",
      "profile_text": "I'm a curious and open-minded person who likes to explore new places and cultures. I also enjoy cooking and preparing healthy meals, and like to stay in shape by practicing yoga. I'm looking for a woman who can share my thirst for adventure and passion for health and well-being."
  }
  ];
  export default profiles
  